### ISSUE TITLE
Return type issue

### ISSUE THREAD

**Issue by roli85** [dotkernel/dot-authentication-web#17]
![2](https://github.com/dotkernel/dot-authentication-web/assets/48314447/b843cd11-45bf-497a-9edd-be82d2bcd716)

need to change return type to following:
![1](https://github.com/dotkernel/dot-authentication-web/assets/48314447/a45dee1b-064a-47ba-a3ff-e4e116155f01)

**Comment by arhimede** [comment]
fixed in #18
